
package org.tusiri.ws.question;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuestionService", targetNamespace = "http://question.ws.tusiri.org/", wsdlLocation = "http://localhost:8080/SOAP-WS/question?wsdl")
public class QuestionService
    extends Service
{

    private final static URL QUESTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUESTIONSERVICE_EXCEPTION;
    private final static QName QUESTIONSERVICE_QNAME = new QName("http://question.ws.tusiri.org/", "QuestionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOAP-WS/question?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUESTIONSERVICE_WSDL_LOCATION = url;
        QUESTIONSERVICE_EXCEPTION = e;
    }

    public QuestionService() {
        super(__getWsdlLocation(), QUESTIONSERVICE_QNAME);
    }

    public QuestionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUESTIONSERVICE_QNAME, features);
    }

    public QuestionService(URL wsdlLocation) {
        super(wsdlLocation, QUESTIONSERVICE_QNAME);
    }

    public QuestionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUESTIONSERVICE_QNAME, features);
    }

    public QuestionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuestionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Question
     */
    @WebEndpoint(name = "QuestionPort")
    public Question getQuestionPort() {
        return super.getPort(new QName("http://question.ws.tusiri.org/", "QuestionPort"), Question.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Question
     */
    @WebEndpoint(name = "QuestionPort")
    public Question getQuestionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://question.ws.tusiri.org/", "QuestionPort"), Question.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUESTIONSERVICE_EXCEPTION!= null) {
            throw QUESTIONSERVICE_EXCEPTION;
        }
        return QUESTIONSERVICE_WSDL_LOCATION;
    }

}
