
package org.tusiri.ws.answer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnswerService", targetNamespace = "http://answer.ws.tusiri.org/", wsdlLocation = "http://localhost:8080/SOAP-WS/answer?wsdl")
public class AnswerService
    extends Service
{

    private final static URL ANSWERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANSWERSERVICE_EXCEPTION;
    private final static QName ANSWERSERVICE_QNAME = new QName("http://answer.ws.tusiri.org/", "AnswerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOAP-WS/answer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANSWERSERVICE_WSDL_LOCATION = url;
        ANSWERSERVICE_EXCEPTION = e;
    }

    public AnswerService() {
        super(__getWsdlLocation(), ANSWERSERVICE_QNAME);
    }

    public AnswerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANSWERSERVICE_QNAME, features);
    }

    public AnswerService(URL wsdlLocation) {
        super(wsdlLocation, ANSWERSERVICE_QNAME);
    }

    public AnswerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANSWERSERVICE_QNAME, features);
    }

    public AnswerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnswerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Answer
     */
    @WebEndpoint(name = "AnswerPort")
    public Answer getAnswerPort() {
        return super.getPort(new QName("http://answer.ws.tusiri.org/", "AnswerPort"), Answer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Answer
     */
    @WebEndpoint(name = "AnswerPort")
    public Answer getAnswerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://answer.ws.tusiri.org/", "AnswerPort"), Answer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANSWERSERVICE_EXCEPTION!= null) {
            throw ANSWERSERVICE_EXCEPTION;
        }
        return ANSWERSERVICE_WSDL_LOCATION;
    }

}
