
package org.tusiri.ws.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "User", targetNamespace = "http://user.ws.tusiri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface User {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws ParseException_Exception
     * @throws ClientProtocolException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://user.ws.tusiri.org/", className = "org.tusiri.ws.user.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://user.ws.tusiri.org/", className = "org.tusiri.ws.user.CreateUserResponse")
    @Action(input = "http://user.ws.tusiri.org/User/createUserRequest", output = "http://user.ws.tusiri.org/User/createUserResponse", fault = {
        @FaultAction(className = ClientProtocolException_Exception.class, value = "http://user.ws.tusiri.org/User/createUser/Fault/ClientProtocolException"),
        @FaultAction(className = IOException_Exception.class, value = "http://user.ws.tusiri.org/User/createUser/Fault/IOException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://user.ws.tusiri.org/User/createUser/Fault/ParseException")
    })
    public int createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws ClientProtocolException_Exception, IOException_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.tusiri.ws.user.UserDetail
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://user.ws.tusiri.org/", className = "org.tusiri.ws.user.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://user.ws.tusiri.org/", className = "org.tusiri.ws.user.GetUserResponse")
    @Action(input = "http://user.ws.tusiri.org/User/getUserRequest", output = "http://user.ws.tusiri.org/User/getUserResponse")
    public UserDetail getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
