
package com.mycompany.nasipadang.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StackExchangeImplService", targetNamespace = "http://jaxws.org/", wsdlLocation = "http://localhost:8001/ws/stackexchange?wsdl")
public class StackExchangeImplService
    extends Service
{

    private final static URL STACKEXCHANGEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STACKEXCHANGEIMPLSERVICE_EXCEPTION;
    private final static QName STACKEXCHANGEIMPLSERVICE_QNAME = new QName("http://jaxws.org/", "StackExchangeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8001/ws/stackexchange?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STACKEXCHANGEIMPLSERVICE_WSDL_LOCATION = url;
        STACKEXCHANGEIMPLSERVICE_EXCEPTION = e;
    }

    public StackExchangeImplService() {
        super(__getWsdlLocation(), STACKEXCHANGEIMPLSERVICE_QNAME);
    }

    public StackExchangeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STACKEXCHANGEIMPLSERVICE_QNAME, features);
    }

    public StackExchangeImplService(URL wsdlLocation) {
        super(wsdlLocation, STACKEXCHANGEIMPLSERVICE_QNAME);
    }

    public StackExchangeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STACKEXCHANGEIMPLSERVICE_QNAME, features);
    }

    public StackExchangeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StackExchangeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StackExchange
     */
    @WebEndpoint(name = "StackExchangeImplPort")
    public StackExchange getStackExchangeImplPort() {
        return super.getPort(new QName("http://jaxws.org/", "StackExchangeImplPort"), StackExchange.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StackExchange
     */
    @WebEndpoint(name = "StackExchangeImplPort")
    public StackExchange getStackExchangeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.org/", "StackExchangeImplPort"), StackExchange.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STACKEXCHANGEIMPLSERVICE_EXCEPTION!= null) {
            throw STACKEXCHANGEIMPLSERVICE_EXCEPTION;
        }
        return STACKEXCHANGEIMPLSERVICE_WSDL_LOCATION;
    }

}
